export default {
  darkMode: 'class',
  content: ['index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  safelist: [
    'bg-background',
    'bg-foreground',
    'bg-primary',
    'bg-secondary',
    'bg-muted',
    'bg-danger',
    'bg-success',
    'bg-info',
    'bg-warn',
    'text-background',
    'text-foreground',
    'text-primary',
    'text-secondary',
    'text-muted',
    'text-danger',
    'text-success',
    'text-info',
    'text-warn',
  ],
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--background))',
        foreground: 'rgb(var(--foreground))',
        primary: 'rgb(var(--primary))',
        secondary: 'rgb(var(--secondary))',
        muted: 'rgb(var(--muted))',
        danger: 'rgb(var(--danger))',
        success: 'rgb(var(--success))',
        info: 'rgb(var(--info))',
        warn: 'rgb(var(--warn))',
      },
    },
    fontFamily: {
      sans: ['"Poppins"', 'sans-serif'],
      mono: ['monospace'],
      icon: ['primeicons'],
    },
  },
};
