export const Paths = {
  HOME: '/',
  CHECKBOX: '/checkbox',
  FORM: '/form',
  LAYERS: '/layers',
  MENUBAR: '/menubar',
  PAGINATION: '/pagination',
  POPPER: '/popper',
  SIDEBAR_FUND: '/sidebar-fund',
  TABLE: '/table',
  EDITOR: '/editor',
  OVERVIEW: '/',
  INSTALL: '/install',
  TREE: '/tree',
  LOADING: '/loading',
};
