name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-example:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm ci
          npm run build:example
      - run: |
          mv ./example ./build
          tar -czf build.tar.gz ./build
      - uses: softprops/action-gh-release@v2
        with:
          files: build.tar.gz
