name: build

on:
  push:
    branches:
      - master

jobs:
  build-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm ci
          npm run build:lib
          npm run build:example
